/**
 * Syntax kinds and node flags for the xbintsc AST.
 *
 * These numeric/string tags are the discriminants used throughout the binder,
 * checker and code generator to switch exhaustively over nodes.
 */

export const enum SyntaxKind {
  // Markers
  Unknown = 0,
  EndOfFileToken = 1,
  SourceFile = 300,
  QualifiedName = 301,
  ExpressionWithTypeArguments = 302,
  ImportType = 303,

  // Trivia-ish
  Identifier = 2,
  PrivateIdentifier = 3,

  // Literals
  NumericLiteral = 4,
  BigIntLiteral = 5,
  StringLiteral = 6,
  NoSubstitutionTemplateLiteral = 7,
  TemplateLiteral = 8,
  TemplateSpan = 9,
  RegularExpressionLiteral = 10,
  TrueKeyword = 11,
  FalseKeyword = 12,
  NullKeyword = 13,
  UndefinedKeyword = 14,
  ThisKeyword = 15,

  // Expressions
  ArrayLiteralExpression = 20,
  ObjectLiteralExpression = 21,
  PropertyAssignment = 22,
  ShorthandPropertyAssignment = 23,
  SpreadElement = 24,
  FunctionExpression = 25,
  ArrowFunction = 26,
  ClassExpression = 27,
  CallExpression = 28,
  NewExpression = 29,
  PropertyAccessExpression = 30,
  ElementAccessExpression = 31,
  ParenthesizedExpression = 32,
  PrefixUnaryExpression = 33,
  PostfixUnaryExpression = 34,
  BinaryExpression = 35,
  ConditionalExpression = 36,
  AsExpression = 37,
  SatisfiesExpression = 38,
  NonNullExpression = 39,
  TypeOfExpression = 40,
  VoidExpression = 41,
  DeleteExpression = 42,
  AwaitExpression = 43,
  YieldExpression = 44,
  TaggedTemplateExpression = 45,
  ArrayBindingPattern = 46,
  ObjectBindingPattern = 47,
  BindingElement = 48,

  // Statements
  ExpressionStatement = 60,
  Block = 61,
  EmptyStatement = 62,
  DebuggerStatement = 63,
  VariableStatement = 64,
  VariableDeclarationList = 65,
  VariableDeclaration = 66,
  IfStatement = 67,
  WhileStatement = 68,
  DoStatement = 69,
  ForStatement = 70,
  ForOfStatement = 71,
  ForInStatement = 72,
  ReturnStatement = 73,
  BreakStatement = 74,
  ContinueStatement = 75,
  ThrowStatement = 76,
  TryStatement = 77,
  CatchClause = 78,
  SwitchStatement = 79,
  CaseClause = 80,
  DefaultClause = 81,
  LabeledStatement = 82,

  // Declarations
  FunctionDeclaration = 100,
  ClassDeclaration = 101,
  InterfaceDeclaration = 102,
  TypeAliasDeclaration = 103,
  EnumDeclaration = 104,
  EnumMember = 105,
  ModuleDeclaration = 106,
  Parameter = 107,
  TypeParameterDeclaration = 108,
  PropertyDeclaration = 109,
  MethodDeclaration = 110,
  ConstructorDeclaration = 111,
  HeritageClause = 112,
  ImportDeclaration = 113,
  ImportClause = 114,
  NamedImports = 115,
  ImportSpecifier = 116,
  NamespaceImport = 117,
  ExportDeclaration = 118,
  ExportAssignment = 119,
  NamedExports = 120,
  ExportSpecifier = 121,

  // Types
  TypeReference = 200,
  TypePredicate = 201,
  AnyKeywordType = 202,
  UnknownKeywordType = 203,
  NumberKeywordType = 204,
  BigIntKeywordType = 205,
  StringKeywordType = 206,
  BooleanKeywordType = 207,
  SymbolKeywordType = 208,
  VoidKeywordType = 209,
  UndefinedKeywordType = 210,
  NullKeywordType = 211,
  NeverKeywordType = 212,
  ObjectKeywordType = 213,
  ThisKeywordType = 214,
  LiteralType = 215,
  ArrayType = 216,
  TupleType = 217,
  UnionType = 218,
  IntersectionType = 219,
  FunctionType = 220,
  TypeLiteral = 221,
  PropertySignature = 222,
  MethodSignature = 223,
  IndexSignature = 224,
  ParenthesizedType = 225,
  TypeQuery = 226,
  IndexedAccessType = 227,
  TypeOperator = 228,
  MappedType = 229,
  ConditionalType = 230,
  InferType = 231,
  OptionalType = 232,
  RestType = 233,
}

export const enum NodeFlags {
  None = 0,
  Let = 1 << 0,
  Const = 1 << 1,
  Var = 1 << 2,
  Exported = 1 << 3,
  Default = 1 << 4,
  Declare = 1 << 5,
  Async = 1 << 6,
  Generator = 1 << 7,
  Ambient = 1 << 8,
  Readonly = 1 << 9,
  Abstract = 1 << 10,
  Optional = 1 << 11,
}

export const enum ModifierKind {
  Export = "export",
  Default = "default",
  Declare = "declare",
  Abstract = "abstract",
  Public = "public",
  Private = "private",
  Protected = "protected",
  Static = "static",
  Readonly = "readonly",
  Async = "async",
  Const = "const",
}
