/**
 * Compile-time application icons.
 *
 * `--icon <file>` (or `app.icon` in `xbintsc.config.json`) reads an icon,
 * validates it and embeds the raw bytes into the produced binary as a small
 * linkable object. The `gui` extension picks the symbols up (weakly) to set the
 * window / Dock icon; the Windows driver additionally turns the icon into a PE
 * resource so Explorer and the taskbar show it. The core compiler never sees
 * any of this — it is a driver concern, exactly like the per-platform linker
 * flags.
 *
 * Supported inputs: `.png` (canonical), `.ico` and `.icns` (best effort on their
 * home platform).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { hashParts } from "./cache.js";
import { compileC, type Runner } from "./toolchain.js";

export type IconFormat = "png" | "ico" | "icns";

export interface IconInfo {
  /** Absolute path the icon was read from. */
  readonly path: string;
  readonly format: IconFormat;
  readonly bytes: Uint8Array;
  /** Intrinsic size where it is cheap to sniff (0 when unknown, e.g. `.icns`). */
  readonly width: number;
  readonly height: number;
}

export class IconError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "IconError";
  }
}

const PNG_MAGIC = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

function startsWith(bytes: Uint8Array, magic: readonly number[]): boolean {
  if (bytes.length < magic.length) return false;
  return magic.every((value, index) => bytes[index] === value);
}

function readUInt32BE(bytes: Uint8Array, offset: number): number {
  return (
    ((bytes[offset]! << 24) | (bytes[offset + 1]! << 16) | (bytes[offset + 2]! << 8) | bytes[offset + 3]!) >>> 0
  );
}

/**
 * Sniff the format from the magic bytes and validate the file. Throws
 * {@link IconError} with an actionable message for missing, empty or
 * unsupported files.
 */
export function readIcon(path: string): IconInfo {
  const absolute = resolve(path);
  if (!existsSync(absolute)) {
    throw new IconError(`Icon file not found: ${absolute}`);
  }
  const bytes = readFileSync(absolute);
  if (bytes.length === 0) {
    throw new IconError(`Icon file is empty: ${absolute}`);
  }

  if (startsWith(bytes, PNG_MAGIC)) {
    // IHDR: width/height are big-endian at offsets 16 and 20.
    const width = bytes.length >= 24 ? readUInt32BE(bytes, 16) : 0;
    const height = bytes.length >= 24 ? readUInt32BE(bytes, 20) : 0;
    return { path: absolute, format: "png", bytes, width, height };
  }

  // ICO / CUR: reserved(2) type(2) count(2), then ICONDIRENTRY[].
  if (bytes.length >= 6 && bytes[0] === 0 && bytes[1] === 0 && bytes[2] === 1 && bytes[3] === 0) {
    const width = bytes.length >= 7 ? bytes[6]! || 256 : 0;
    const height = bytes.length >= 8 ? bytes[7]! || 256 : 0;
    return { path: absolute, format: "ico", bytes, width, height };
  }

  if (startsWith(bytes, [0x69, 0x63, 0x6e, 0x73])) {
    return { path: absolute, format: "icns", bytes, width: 0, height: 0 };
  }

  throw new IconError(
    `Unsupported icon format: ${absolute} (expected a PNG, ICO or ICNS file)`,
  );
}

/** The C symbols the embedded icon exposes to the runtime (and native code). */
export const ICON_SYMBOLS = {
  data: "xt_app_icon_data",
  size: "xt_app_icon_size",
  format: "xt_app_icon_format",
  width: "xt_app_icon_width",
  height: "xt_app_icon_height",
} as const;

/**
 * A zero-length icon. The GUI extension references {@link ICON_SYMBOLS}
 * unconditionally, so the driver links this object into GUI programs even when
 * no icon is configured; `size == 0` tells the runtime to skip it.
 */
export const EMPTY_ICON: IconInfo = {
  path: "",
  format: "png",
  bytes: new Uint8Array(0),
  width: 0,
  height: 0,
};

/** Generate the C translation unit embedding the icon bytes. */
export function iconSource(icon: IconInfo): string {
  const lines: string[] = [];
  const bytes = icon.bytes;
  for (let offset = 0; offset < bytes.length; offset += 16) {
    const chunk = Array.from(bytes.subarray(offset, offset + 16), (byte) => `0x${byte.toString(16).padStart(2, "0")}`);
    lines.push("  " + chunk.join(", ") + ",");
  }
  // A zero-length array is not portable C, so an empty icon still emits one
  // placeholder byte while reporting `size == 0`.
  if (lines.length === 0) lines.push("  0x00,");
  return [
    "/* Generated by xbintsc — embedded application icon. Do not edit. */",
    `const unsigned char ${ICON_SYMBOLS.data}[] = {`,
    ...lines,
    "};",
    `const unsigned long long ${ICON_SYMBOLS.size} = ${bytes.length}ull;`,
    `const char ${ICON_SYMBOLS.format}[] = "${icon.format}";`,
    `const unsigned int ${ICON_SYMBOLS.width} = ${icon.width}u;`,
    `const unsigned int ${ICON_SYMBOLS.height} = ${icon.height}u;`,
    "",
  ].join("\n");
}

/**
 * Compile the icon into an object exposing {@link ICON_SYMBOLS}. Cached by the
 * icon contents, so an unchanged icon is never recompiled.
 */
export function ensureIconObject(
  runner: Runner,
  clang: string,
  cacheDir: string,
  icon: IconInfo,
  env?: Record<string, string>,
): string {
  const key = hashParts(["icon", process.platform, Buffer.from(icon.bytes).toString("base64")]);
  const sourcePath = join(cacheDir, `icon-${key}.c`);
  const objectPath = join(cacheDir, `icon-${key}.o`);
  if (!existsSync(objectPath)) {
    mkdirSync(cacheDir, { recursive: true });
    writeFileSync(sourcePath, iconSource(icon));
    compileC(runner, clang, sourcePath, objectPath, cacheDir, env);
  }
  return objectPath;
}

/**
 * Wrap a PNG in a minimal ICO container. Vista+ accepts a PNG payload directly,
 * so the PE resource path needs no BMP encoder.
 */
export function pngToIco(png: Uint8Array, width: number, height: number): Uint8Array {
  const header = Buffer.alloc(22);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(1, 4); // image count
  header.writeUInt8(width >= 256 || width <= 0 ? 0 : width, 6);
  header.writeUInt8(height >= 256 || height <= 0 ? 0 : height, 7);
  header.writeUInt8(0, 8); // palette size
  header.writeUInt8(0, 9); // reserved
  header.writeUInt16LE(1, 10); // color planes
  header.writeUInt16LE(32, 12); // bits per pixel
  header.writeUInt32LE(png.length, 14);
  header.writeUInt32LE(22, 18); // payload offset
  return Buffer.concat([header, Buffer.from(png)]);
}

/** Normalize any supported icon to ICO bytes (used for the PE resource). */
export function toIcoBytes(icon: IconInfo): Uint8Array {
  if (icon.format === "ico") return icon.bytes;
  if (icon.format === "png") return pngToIco(icon.bytes, icon.width, icon.height);
  throw new IconError(`Cannot embed a .${icon.format} icon as a Windows PE resource; use a PNG or ICO.`);
}
