/**
 * Windows GUI-subsystem entry point.
 *
 * A program that links with the `gui` extension is built as a **Windows
 * subsystem** executable (`/SUBSYSTEM:WINDOWS`), which is what keeps a console
 * window from flashing up when it is launched. The MSVC C runtime then expects
 * `WinMain` instead of `main`, and xbintsc's runtime always emits a C `main`
 * (the program body plus teardown), so the driver links this tiny shim to
 * bridge the two.
 *
 * It is compiled on demand and cached like the icon object; nothing here is
 * platform-abstract — on every other platform the file is never used.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { hashParts } from "./cache.js";
import { compileC, type Runner } from "./toolchain.js";

/** The bridge source. `main` is the entry point the runtime emits. */
export const WINDOWS_ENTRY_SOURCE = `/* Generated by xbintsc - Windows GUI subsystem entry point. Do not edit. */
#ifndef UNICODE
#define UNICODE
#endif
#include <windows.h>

/* The xbintsc runtime defines the C program entry point; hand it the command
 * line minus the argv[0] hole so it still sees its own arguments. */
int main(int argc, char **argv);

int WINAPI WinMain(HINSTANCE instance, HINSTANCE previous, LPSTR command_line, int show) {
  (void)instance;
  (void)previous;
  (void)command_line;
  (void)show;
  return main(__argc, __argv);
}
`;

/**
 * Compile the entry shim into an object file (cached by source + platform +
 * toolchain) and return its path.
 */
export function ensureWindowsEntryObject(
  runner: Runner,
  clang: string,
  cacheDir: string,
  env?: Record<string, string>,
): string {
  const key = hashParts(["win-gui-entry", process.platform, clang, WINDOWS_ENTRY_SOURCE]);
  const sourcePath = join(cacheDir, `winentry-${key}.c`);
  const objectPath = join(cacheDir, `winentry-${key}.o`);
  if (!existsSync(objectPath)) {
    mkdirSync(cacheDir, { recursive: true });
    writeFileSync(sourcePath, WINDOWS_ENTRY_SOURCE);
    compileC(runner, clang, sourcePath, objectPath, cacheDir, env);
  }
  return objectPath;
}
