/**
 * Token taxonomy for the xbintsc lexer. Kept close to the TypeScript grammar so
 * the parser can stay a direct recursive-descent transcription of the spec.
 */

export enum TokenKind {
  EndOfFile = "EndOfFile",
  Identifier = "Identifier",
  PrivateIdentifier = "PrivateIdentifier",
  NumericLiteral = "NumericLiteral",
  BigIntLiteral = "BigIntLiteral",
  StringLiteral = "StringLiteral",
  NoSubstitutionTemplateLiteral = "NoSubstitutionTemplateLiteral",
  TemplateHead = "TemplateHead",
  TemplateMiddle = "TemplateMiddle",
  TemplateTail = "TemplateTail",
  RegularExpressionLiteral = "RegularExpressionLiteral",

  // Punctuation
  OpenBrace = "{",
  CloseBrace = "}",
  OpenParen = "(",
  CloseParen = ")",
  OpenBracket = "[",
  CloseBracket = "]",
  Dot = ".",
  DotDotDot = "...",
  Semicolon = ";",
  Comma = ",",
  LessThan = "<",
  GreaterThan = ">",
  LessThanEquals = "<=",
  GreaterThanEquals = ">=",
  EqualsEquals = "==",
  ExclamationEquals = "!=",
  EqualsEqualsEquals = "===",
  ExclamationEqualsEquals = "!==",
  EqualsGreaterThan = "=>",
  Plus = "+",
  Minus = "-",
  Asterisk = "*",
  AsteriskAsterisk = "**",
  Slash = "/",
  Percent = "%",
  PlusPlus = "++",
  MinusMinus = "--",
  LessThanLessThan = "<<",
  GreaterThanGreaterThan = ">>",
  GreaterThanGreaterThanGreaterThan = ">>>",
  Ampersand = "&",
  Bar = "|",
  Caret = "^",
  Exclamation = "!",
  Tilde = "~",
  AmpersandAmpersand = "&&",
  BarBar = "||",
  Question = "?",
  Colon = ":",
  Equals = "=",
  PlusEquals = "+=",
  MinusEquals = "-=",
  AsteriskEquals = "*=",
  AsteriskAsteriskEquals = "**=",
  SlashEquals = "/=",
  PercentEquals = "%=",
  LessThanLessThanEquals = "<<=",
  GreaterThanGreaterThanEquals = ">>=",
  GreaterThanGreaterThanGreaterThanEquals = ">>>=",
  AmpersandEquals = "&=",
  BarEquals = "|=",
  CaretEquals = "^=",
  AmpersandAmpersandEquals = "&&=",
  BarBarEquals = "||=",
  QuestionQuestionEquals = "??=",
  QuestionQuestion = "??",
  QuestionDot = "?.",
  At = "@",
  Hash = "#",
  Backtick = "`",

  // Keywords (subset that xbintsc understands today, but the full set is tokenized
  // so the parser can produce good "unsupported" diagnostics rather than
  // confusing "unexpected token" errors).
  AbstractKeyword = "abstract",
  AnyKeyword = "any",
  AsKeyword = "as",
  AssertsKeyword = "asserts",
  AsyncKeyword = "async",
  AwaitKeyword = "await",
  BigIntKeyword = "bigint",
  BooleanKeyword = "boolean",
  BreakKeyword = "break",
  CaseKeyword = "case",
  CatchKeyword = "catch",
  ClassKeyword = "class",
  ConstKeyword = "const",
  ConstructorKeyword = "constructor",
  ContinueKeyword = "continue",
  DebuggerKeyword = "debugger",
  DeclareKeyword = "declare",
  DefaultKeyword = "default",
  DeleteKeyword = "delete",
  DoKeyword = "do",
  ElseKeyword = "else",
  EnumKeyword = "enum",
  ExportKeyword = "export",
  ExtendsKeyword = "extends",
  FalseKeyword = "false",
  FinallyKeyword = "finally",
  ForKeyword = "for",
  FromKeyword = "from",
  FunctionKeyword = "function",
  GetKeyword = "get",
  IfKeyword = "if",
  ImplementsKeyword = "implements",
  ImportKeyword = "import",
  InKeyword = "in",
  InferKeyword = "infer",
  InstanceOfKeyword = "instanceof",
  InterfaceKeyword = "interface",
  IsKeyword = "is",
  KeyOfKeyword = "keyof",
  LetKeyword = "let",
  ModuleKeyword = "module",
  NamespaceKeyword = "namespace",
  NeverKeyword = "never",
  NewKeyword = "new",
  NullKeyword = "null",
  NumberKeyword = "number",
  ObjectKeyword = "object",
  PackageKeyword = "package",
  PrivateKeyword = "private",
  ProtectedKeyword = "protected",
  PublicKeyword = "public",
  ReadonlyKeyword = "readonly",
  ReturnKeyword = "return",
  SatisfiesKeyword = "satisfies",
  SetKeyword = "set",
  StaticKeyword = "static",
  StringKeyword = "string",
  SuperKeyword = "super",
  SwitchKeyword = "switch",
  SymbolKeyword = "symbol",
  ThisKeyword = "this",
  ThrowKeyword = "throw",
  TrueKeyword = "true",
  TryKeyword = "try",
  TypeKeyword = "type",
  TypeOfKeyword = "typeof",
  UndefinedKeyword = "undefined",
  UniqueKeyword = "unique",
  UnknownKeyword = "unknown",
  VarKeyword = "var",
  VoidKeyword = "void",
  WhileKeyword = "while",
  WithKeyword = "with",
  YieldKeyword = "yield",
}

export interface Token {
  readonly kind: TokenKind;
  readonly start: number;
  readonly end: number;
  /** Raw source text of the token. */
  readonly text: string;
  /** Decoded value for string/number/template tokens. */
  readonly value?: string | number | bigint;
  /** True when a newline appeared between the previous token and this one. */
  readonly precededByLineBreak: boolean;
}

export const KEYWORDS = new Map<string, TokenKind>([
  ["abstract", TokenKind.AbstractKeyword],
  ["any", TokenKind.AnyKeyword],
  ["as", TokenKind.AsKeyword],
  ["asserts", TokenKind.AssertsKeyword],
  ["async", TokenKind.AsyncKeyword],
  ["await", TokenKind.AwaitKeyword],
  ["bigint", TokenKind.BigIntKeyword],
  ["boolean", TokenKind.BooleanKeyword],
  ["break", TokenKind.BreakKeyword],
  ["case", TokenKind.CaseKeyword],
  ["catch", TokenKind.CatchKeyword],
  ["class", TokenKind.ClassKeyword],
  ["const", TokenKind.ConstKeyword],
  ["constructor", TokenKind.ConstructorKeyword],
  ["continue", TokenKind.ContinueKeyword],
  ["debugger", TokenKind.DebuggerKeyword],
  ["declare", TokenKind.DeclareKeyword],
  ["default", TokenKind.DefaultKeyword],
  ["delete", TokenKind.DeleteKeyword],
  ["do", TokenKind.DoKeyword],
  ["else", TokenKind.ElseKeyword],
  ["enum", TokenKind.EnumKeyword],
  ["export", TokenKind.ExportKeyword],
  ["extends", TokenKind.ExtendsKeyword],
  ["false", TokenKind.FalseKeyword],
  ["finally", TokenKind.FinallyKeyword],
  ["for", TokenKind.ForKeyword],
  ["from", TokenKind.FromKeyword],
  ["function", TokenKind.FunctionKeyword],
  ["get", TokenKind.GetKeyword],
  ["if", TokenKind.IfKeyword],
  ["implements", TokenKind.ImplementsKeyword],
  ["import", TokenKind.ImportKeyword],
  ["in", TokenKind.InKeyword],
  ["infer", TokenKind.InferKeyword],
  ["instanceof", TokenKind.InstanceOfKeyword],
  ["interface", TokenKind.InterfaceKeyword],
  ["is", TokenKind.IsKeyword],
  ["keyof", TokenKind.KeyOfKeyword],
  ["let", TokenKind.LetKeyword],
  ["module", TokenKind.ModuleKeyword],
  ["namespace", TokenKind.NamespaceKeyword],
  ["never", TokenKind.NeverKeyword],
  ["new", TokenKind.NewKeyword],
  ["null", TokenKind.NullKeyword],
  ["number", TokenKind.NumberKeyword],
  ["object", TokenKind.ObjectKeyword],
  ["package", TokenKind.PackageKeyword],
  ["private", TokenKind.PrivateKeyword],
  ["protected", TokenKind.ProtectedKeyword],
  ["public", TokenKind.PublicKeyword],
  ["readonly", TokenKind.ReadonlyKeyword],
  ["return", TokenKind.ReturnKeyword],
  ["satisfies", TokenKind.SatisfiesKeyword],
  ["set", TokenKind.SetKeyword],
  ["static", TokenKind.StaticKeyword],
  ["string", TokenKind.StringKeyword],
  ["super", TokenKind.SuperKeyword],
  ["switch", TokenKind.SwitchKeyword],
  ["symbol", TokenKind.SymbolKeyword],
  ["this", TokenKind.ThisKeyword],
  ["throw", TokenKind.ThrowKeyword],
  ["true", TokenKind.TrueKeyword],
  ["try", TokenKind.TryKeyword],
  ["type", TokenKind.TypeKeyword],
  ["typeof", TokenKind.TypeOfKeyword],
  ["undefined", TokenKind.UndefinedKeyword],
  ["unique", TokenKind.UniqueKeyword],
  ["unknown", TokenKind.UnknownKeyword],
  ["var", TokenKind.VarKeyword],
  ["void", TokenKind.VoidKeyword],
  ["while", TokenKind.WhileKeyword],
  ["with", TokenKind.WithKeyword],
  ["yield", TokenKind.YieldKeyword],
]);

/**
 * Keywords that are allowed in identifier position in some contexts and should
 * therefore not be treated as hard errors when used as a name.
 */
export const CONTEXTUAL_KEYWORDS: ReadonlySet<TokenKind> = new Set([
  TokenKind.AsKeyword,
  TokenKind.SatisfiesKeyword,
  TokenKind.FromKeyword,
  TokenKind.TypeKeyword,
  TokenKind.GetKeyword,
  TokenKind.SetKeyword,
  TokenKind.AsyncKeyword,
]);

/** True when the token text is the contextual `of` keyword. */
export function isOfKeyword(token: Token): boolean {
  return token.kind === TokenKind.Identifier && token.text === "of";
}

/** Every keyword token kind, derived from the scanner's keyword table. */
export const KEYWORD_KINDS: ReadonlySet<TokenKind> = new Set(KEYWORDS.values());

/**
 * True for the hard/contextual keywords the scanner emits. Property names and
 * member access allow any of these (`obj.default`, `{ type: 1 }`), so the
 * parser consults this instead of maintaining a hand-written allow list.
 */
export function isKeywordKind(kind: TokenKind): boolean {
  return KEYWORD_KINDS.has(kind);
}

/**
 * Keywords that can never be used as a plain binding/identifier. Everything
 * else the scanner recognizes is a TypeScript contextual keyword (`type`,
 * `async`, `module`, `namespace`, `readonly`, …) and may legally name a
 * variable, parameter or property.
 */
const RESERVED_KEYWORDS: ReadonlySet<TokenKind> = new Set([
  TokenKind.BreakKeyword,
  TokenKind.CaseKeyword,
  TokenKind.CatchKeyword,
  TokenKind.ClassKeyword,
  TokenKind.ConstKeyword,
  TokenKind.ContinueKeyword,
  TokenKind.DebuggerKeyword,
  TokenKind.DefaultKeyword,
  TokenKind.DeleteKeyword,
  TokenKind.DoKeyword,
  TokenKind.ElseKeyword,
  TokenKind.EnumKeyword,
  TokenKind.ExportKeyword,
  TokenKind.ExtendsKeyword,
  TokenKind.FalseKeyword,
  TokenKind.FinallyKeyword,
  TokenKind.ForKeyword,
  TokenKind.FunctionKeyword,
  TokenKind.IfKeyword,
  TokenKind.ImportKeyword,
  TokenKind.InKeyword,
  TokenKind.InstanceOfKeyword,
  TokenKind.NewKeyword,
  TokenKind.NullKeyword,
  TokenKind.ReturnKeyword,
  TokenKind.SuperKeyword,
  TokenKind.SwitchKeyword,
  TokenKind.ThisKeyword,
  TokenKind.ThrowKeyword,
  TokenKind.TrueKeyword,
  TokenKind.TryKeyword,
  TokenKind.TypeOfKeyword,
  TokenKind.VarKeyword,
  TokenKind.VoidKeyword,
  TokenKind.WhileKeyword,
  TokenKind.WithKeyword,
  // Strict-mode / module reserved words.
  TokenKind.LetKeyword,
  TokenKind.StaticKeyword,
  TokenKind.YieldKeyword,
  TokenKind.AwaitKeyword,
  TokenKind.ImplementsKeyword,
  TokenKind.InterfaceKeyword,
  TokenKind.PackageKeyword,
  TokenKind.PrivateKeyword,
  TokenKind.ProtectedKeyword,
  TokenKind.PublicKeyword,
]);

/** True when the scanner token may be used as an identifier/binding name. */
export function isIdentifierNameToken(kind: TokenKind): boolean {
  return kind === TokenKind.Identifier || (isKeywordKind(kind) && !RESERVED_KEYWORDS.has(kind));
}
